export const FETCH_PRODUCTS ='FETCH_PRODUCTS';
export const PRODUCTS_DETAILS_REQUEST  = 'PRODUCTS_DETAILS_REQUEST';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';